server:
  port: 8761

spring:
   application:
     name: lhwgy-eureka
   cloud:
     config:
       server:
         git:
           uri: https://github.com/yz0812/lhwgy-orderfood.git
           searchPaths: file
  #          username: yz0812
  #          password: 8752885w
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    prefer-ip-address:  true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
