server:
  port: 8763

spring:
   application:
     name: lhwgy-web
   thymeleaf:
     cache: false
     encoding: UTF-8
     content-type: text/html
     mode: LEGACYHTML5
#   mvc:
  #   static-path-pattern: /static/**
#   resources:
  #   static-locations: classpath:/static/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true