server:
  port: 8762

  # git管理配置
spring:
  application:
    name: lhwgy-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yz0812/lhwgy-orderfood.git
          searchPaths: file
  #          username: yz0812
  #          password: 8752885w
# 配置服务注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/